definitions:
  auth.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.RegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.Category:
    properties:
      color:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      isDefault:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
      userID:
        description: nil для дефолтных категорий
        type: integer
    type: object
  response.ErrorResponse:
    description: Стандартный ответ при ошибке
    properties:
      error:
        type: string
    type: object
  response.SuccessResponse:
    description: Стандартный ответ при успешном выполнении
    properties:
      message:
        type: string
    type: object
  response.TokenResponse:
    properties:
      token:
        example: Ваш токен
        type: string
    type: object
  transactions.TransactionInput:
    properties:
      amount:
        type: integer
      bonusChange:
        type: number
      category:
        type: integer
      currency:
        type: string
      date:
        type: string
      description:
        type: string
      title:
        type: string
      type:
        enum:
        - income
        - expense
        type: string
      typeBonus:
        type: string
    required:
    - amount
    - title
    - type
    type: object
  сategory.CreateCategoryInput:
    properties:
      color:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  сategory.UpdateCategoryInput:
    properties:
      color:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  title: Персональный финансовый менеджер
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя с указанием почты и пароля
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная авторизация
          schema:
            $ref: '#/definitions/response.TokenResponse'
        "400":
          description: Описание ошибки валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Неверный пароль
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Пользователя с такой почтой не существует
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Авторизация
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Регистрация пользователя с указанием никнейма, почты, пароля
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Успешная регистрация
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Описание ошибки валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Почта уже зарегистрированы
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Не удалось хешировать пароль или создать пользователя
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - auth
  /categories:
    get:
      description: Получить все категории пользователя или категории по умолчанию
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "500":
          description: Ошибка при получении категорий
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить категории
      tags:
      - Categories
    post:
      consumes:
      - application/json
      description: Создать новую категорию для пользователя
      parameters:
      - description: Категория для создания
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/%D1%81ategory.CreateCategoryInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Category'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка создания категории
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать категорию
      tags:
      - Categories
  /categories/{id}:
    delete:
      description: Удалить категорию пользователя
      parameters:
      - description: ID категории
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Категория успешно удалена
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "500":
          description: Ошибка удаления категории
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Удалить категорию
      tags:
      - Categories
    put:
      consumes:
      - application/json
      description: Обновить информацию о категории пользователя
      parameters:
      - description: ID категории
        in: path
        name: id
        required: true
        type: string
      - description: Категория для обновления
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/%D1%81ategory.UpdateCategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: Категория успешно обновлена
          schema:
            $ref: '#/definitions/models.Category'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Категория не найдена
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка обновления категории
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Обновить категорию
      tags:
      - Categories
  /transactions:
    post:
      consumes:
      - application/json
      description: Создает новую транзакцию для пользователя
      parameters:
      - description: Транзакция для создания
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/transactions.TransactionInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/transactions.TransactionInput'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка создания транзакции
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать транзакцию
      tags:
      - Transactions
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
